// index.js
import './public/images/3760-illustration-of-blue-and-purple-right-arrows-pv.png'
import './public/images/404.jpg'
import './public/images/chto-luchshe.jpg'
import './public/images/favicon-32x32.png'
import './public/images/Hd3fb19e1e5-photoaidcom-cropped.jpg'
import './public/images/menu-comments.png'
import './public/images/Rotating-Globe-from-Wikipedia.gif'
import './public/images/globus.jpg'

import './public/img/08c27d291990c86bc01cc4f9d640e8b2.jpg'
import './public/img/15y675esk3g.jpg'
import './public/img/34.jpg'
import './public/img/845x845.webp'
import './public/img/ÐÐ¾Ð»Ð¾Ð¼Ð¸ÑÐ¾Ð²ÑÐµ ÐÐ»ÑÐ¿Ñ.jpg'
import './public/img/ÐÐ¾Ð»Ð¾Ð¼Ð¸ÑÐ¾Ð²ÑÐµ ÐÐ»ÑÐ¿Ñ1.jpg'
import './public/img/Ð ÐµÐ¹Ð½ÑÐºÐ¸Ð¹ Ð²Ð¾Ð´Ð¾Ð¿Ð°Ð´.jpg'
import './public/img/Ð ÐµÐ¹Ð½ÑÐºÐ¸Ð¹ Ð²Ð¾Ð´Ð¾Ð¿Ð°Ð´1.jpeg'

import './public/img/Ð ÐµÐ¹Ð½ÑÐºÐ¸Ð¹ Ð²Ð¾Ð´Ð¾Ð¿Ð°Ð´2.jpg'
import './public/img/Ð ÐµÐ¹Ð½ÑÐºÐ¸Ð¹ Ð²Ð¾Ð´Ð¾Ð¿Ð°Ð´3.jpg'
import './public/img/Ð ÐµÐ¹Ð½ÑÐºÐ¸Ð¹ Ð²Ð¾Ð´Ð¾Ð¿Ð°Ð´4.jpeg'
import './public/img/Ð¥Ð¾Ð±Ð±Ð¸ÑÐ¾Ð½1.jpg'
import './public/img/Ð¥Ð¾Ð±Ð±Ð¸ÑÐ¾Ð½2.jpg'
import './public/img/gorod-kolmar.jpg'
import './public/img/egipetskie-piramidy_89.jpg'
import './public/img/gorod-kolmar1.jpg'
import './public/img/gorod-kolmar2.jpg'
import './public/img/likeRed.png'
import './public/img/tibet_213.jpg'
import './public/img/tibet_214.jpg'
import './public/img/tibet_217.jpg'

import './public/js/comment.js'
import './public/js/delete.js'
import './public/js/exit.js'
import './public/js/headerBtnActive.js'
import './public/js/index.js'
import './public/js/moderator.js'
import './public/js/registration.js'
import './public/js/replyCommit.js'

import './public/styles/addPhoto.css'
import './public/styles/admin.css'
import './public/styles/adminPanel.css'
import './public/styles/header.css'
import './public/styles/moderator.css'
import './public/styles/profile.css'
import './public/styles/registration.css'
import './public/styles/style.css'

